"""Introduction of category and its foreign key to existing tables

Revision ID: e06ca80cc12f
Revises: 85c5be65438f
Create Date: 2024-02-27 13:56:02.229185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06ca80cc12f'
down_revision: Union[str, None] = '85c5be65438f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounting', 'categories', ['category_id'], ['id'])
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'])
    op.add_column('income', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'category_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'category_id')
    op.drop_constraint(None, 'accounting', type_='foreignkey')
    op.drop_column('accounting', 'category_id')
    # ### end Alembic commands ###
